apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: echo-ingress
  namespace: openfaas
spec:
  rules:
  - host: echo1.pgr095.tk
    http:
      paths:
      - backend:
          serviceName: echo1
          servicePort: 80